# Generated by Django 3.2.6 on 2022-05-26 11:35

from django.db import migrations, models
import schedulio.djangoapp.models
import schedulio.djangoapp.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(default=schedulio.djangoapp.models.new_uuid, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('create_time', models.DateTimeField(default=schedulio.djangoapp.time.now)),
            ],
        ),
    ]
