# Generated by Django 4.0.4 on 2022-05-27 15:17

from django.db import migrations, models
import django.db.models.deletion
import schedulio.djangoapp.models
import schedulio.djangoapp.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(default=schedulio.djangoapp.models.new_uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.IntegerField(default=schedulio.djangoapp.time.now_timestamp)),
                ('last_update', models.IntegerField(default=schedulio.djangoapp.time.now_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(default=schedulio.djangoapp.models.new_uuid, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('create_time', models.IntegerField(default=schedulio.djangoapp.time.now_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(default=schedulio.djangoapp.models.new_uuid, max_length=36, primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_index=True)),
                ('answer', models.CharField(max_length=255)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.guest')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.schedule'),
        ),
    ]
