# Generated by Django 4.0.4 on 2022-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
