# Generated by Django 4.0.4 on 2022-06-07 13:48

from django.db import migrations, models
import schedulio.djangoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='path_id',
            field=models.CharField(default=schedulio.djangoapp.models.new_uuid, max_length=64),
        ),
    ]
